import {test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();
const customer='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002',staff='00000000-0000-4000-8000-000000000003',unverified='00000000-0000-4000-8000-000000000004';
before(async()=>{await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key,phone text,phone_confirmed_at timestamptz,email text,email_confirmed_at timestamptz,is_anonymous boolean default false); create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$; create function auth.uid() returns uuid language sql stable as $$select (auth.jwt()->>'sub')::uuid$$; grant usage on schema auth to anon,authenticated; grant execute on function auth.jwt(),auth.uid() to anon,authenticated;`);await db.exec(await readFile('supabase/migrations/001_secure_ordering.sql','utf8'));await db.exec(await readFile('supabase/migrations/002_staff_roles.sql','utf8'));await db.exec(`insert into auth.users(id,phone,phone_confirmed_at,email,email_confirmed_at) values ('${customer}','919999999991',now(),'one@example.com',now()),('${other}','919999999992',now(),'two@example.com',now()),('${staff}','919999999993',now(),'staff@example.com',now()),('${unverified}','919999999994',null,'unverified@example.com',null); insert into private.staff(user_id,role) values('${staff}','manager'); insert into public.menu_items values('dish','Dosa','Dosa','Crispy',9000,null,true),('inactive','Unavailable','Dosa','',5000,null,false);`);});
after(()=>db.close());
beforeEach(async()=>{await db.exec(`update private.staff set role='manager',active=true where user_id='${staff}'; delete from private.staff where user_id<>'${staff}'; truncate private.staff_audit;`);await db.exec('reset role; truncate public.orders,private.order_audit restart identity; update public.ordering_settings set enabled=true,auth_channel=\'phone\';');});
async function as(user,fn,{role='authenticated',aal='aal1',fresh=true}={}){await db.exec('begin');try{await db.query(`select set_config('request.jwt.claims',$1,true)`,[JSON.stringify({sub:user,aal,amr:[{method:'otp',timestamp:Math.floor(Date.now()/1000)-(fresh?0:7200)}]})]);await db.exec('set local role '+role);const r=await fn();await db.exec('commit');return r;}catch(e){await db.exec('rollback');throw e;}}
async function place(q=1,overrides={}){const args={request:randomUUID(),items:[{id:'dish',quantity:q}],name:'Test customer',mode:'pickup',table:null,notes:'',total:q*9000,...overrides};const r=await db.query('select * from public.place_order($1::uuid,$2::jsonb,$3,$4,$5::integer,$6,$7::integer)',[args.request,JSON.stringify(args.items),args.name,args.mode,args.table,args.notes,args.total]);return r.rows[0];}
const transition=async(id,action,note='')=>{const r=await db.query('select public.staff_transition($1::uuid,$2,$3) ticket',[id,action,note]);return {rows:r.rows.map(x=>x.ticket)};};
test('anonymous cannot submit',()=>assert.rejects(as(null,()=>place(),{role:'anon'})));
test('unverified identity cannot submit',()=>assert.rejects(as(unverified,()=>place()),/Verify/));
test('expired OTP authentication cannot submit',()=>assert.rejects(as(customer,()=>place(),{fresh:false}),/fresh verification/));
test('disabled ordering fails closed',async()=>{await db.exec('update public.ordering_settings set enabled=false');await assert.rejects(as(customer,()=>place()),/not accepting/);});
test('10 total portions await acceptance; 11 require a call',async()=>{const a=await as(customer,()=>place(10));const b=await as(other,()=>place(11));assert.equal(a.status,'pending_acceptance');assert.equal(b.status,'awaiting_call');assert.equal(b.dish_count,11);assert.equal(b.total_paise,99000);});
test('tampered totals are rejected',()=>assert.rejects(as(customer,()=>place(1,{total:1})),/prices have changed/));
test('client prices cannot be added to item payload',()=>assert.rejects(as(customer,()=>place(1,{items:[{id:'dish',quantity:1,price_paise:1}]})),/Invalid item/));
test('negative and fractional quantities rejected',async()=>{for(const quantity of [-1,0,1.5,'1.5',null])await assert.rejects(as(customer,()=>place(1,{items:[{id:'dish',quantity}]})),/quantity/);});
test('duplicate item IDs rejected',()=>assert.rejects(as(customer,()=>place(2,{items:[{id:'dish',quantity:1},{id:'dish',quantity:1}]})),/Duplicate/));
test('inactive dishes rejected',()=>assert.rejects(as(customer,()=>place(1,{items:[{id:'inactive',quantity:1}]})),/no longer available/));
test('idempotent retry returns the same order',async()=>{const request=randomUUID();const a=await as(customer,()=>place(1,{request}));const b=await as(customer,()=>place(1,{request}));assert.equal(a.id,b.id);assert.equal((await db.query('select count(*)::int n from public.orders')).rows[0].n,1);});
test('active order prevents splitting large orders',async()=>{await as(customer,()=>place(10));await assert.rejects(as(customer,()=>place(1)),/active order/);});
test('customer cannot insert/update tables directly',async()=>{await assert.rejects(as(customer,()=>db.exec("update public.orders set status='queued'")),/permission denied/);await assert.rejects(as(customer,()=>db.exec('update public.menu_items set price_paise=1')),/permission denied/);await assert.rejects(as(customer,()=>db.exec('update public.ordering_settings set enabled=true')),/permission denied/);});
test('customers cannot read other customers orders',async()=>{await as(customer,()=>place());const r=await as(other,()=>db.query('select * from public.orders'));assert.equal(r.rows.length,0);});
test('public cannot read orders or staff records',async()=>{await assert.rejects(as(null,()=>db.query('select * from public.orders'),{role:'anon'}));await assert.rejects(as(customer,()=>db.query('select * from private.staff')));});
test('customers cannot approve; staff require MFA',async()=>{const o=await as(customer,()=>place());await assert.rejects(as(customer,()=>transition(o.id,'accept'),{aal:'aal2'}),/Staff access/);await assert.rejects(as(staff,()=>transition(o.id,'accept')),/authenticator/);});
test('large order cannot bypass call confirmation',async()=>{const o=await as(customer,()=>place(11));await assert.rejects(as(staff,()=>transition(o.id,'accept'),{aal:'aal2'}),/not allowed/);await assert.rejects(as(staff,()=>transition(o.id,'confirm_call','yes'),{aal:'aal2'}),/Record who/);const r=await as(staff,()=>transition(o.id,'confirm_call','Spoke to customer and kitchen; quantities and pickup confirmed.'),{aal:'aal2'});assert.equal(r.rows[0].status,'queued');assert.equal(r.rows[0].call_confirmed_by,staff);assert.ok(r.rows[0].call_confirmed_at);});
test('staff transitions must follow queue lifecycle',async()=>{const o=await as(customer,()=>place());await assert.rejects(as(staff,()=>transition(o.id,'ready'),{aal:'aal2'}),/not allowed/);for(const [action,status] of [['accept','queued'],['prepare','preparing'],['ready','ready'],['complete','completed']])assert.equal((await as(staff,()=>transition(o.id,action),{aal:'aal2'})).rows[0].status,status);assert.equal((await db.query('select count(*)::int n from private.order_audit')).rows[0].n,5);});
test('stale requests cannot enter kitchen',async()=>{const o=await as(customer,()=>place());await db.query("update public.orders set created_at=now()-interval '2 hours' where id=$1",[o.id]);await assert.rejects(as(staff,()=>transition(o.id,'accept'),{aal:'aal2'}),/expired/);});
test('customer can cancel only own unaccepted request',async()=>{const o=await as(customer,()=>place());await assert.rejects(as(other,()=>db.query('select public.cancel_order($1)',[o.id])));await as(customer,()=>db.query('select public.cancel_order($1)',[o.id]));assert.equal((await db.query('select status from public.orders')).rows[0].status,'cancelled');});
test('burst rate limit applies after cancellations too',async()=>{for(let i=0;i<3;i++){const o=await as(customer,()=>place());await as(customer,()=>db.query('select public.cancel_order($1)',[o.id]));}await assert.rejects(as(customer,()=>place()),/Too many/);});
test('table validation and oversized notes enforced',async()=>{await assert.rejects(as(customer,()=>place(1,{mode:'dine_in',table:11})),/valid pickup/);await assert.rejects(as(customer,()=>place(1,{notes:'a'.repeat(501)})),/notes/);});
test('email auth can be selected server-side',async()=>{await db.exec("update public.ordering_settings set auth_channel='email'");const o=await as(customer,()=>place());assert.equal(o.contact,'one@example.com');});

const rpc=(name,args=[])=>db.query(name,args);
async function roleAs(r){await db.query('update private.staff set role=$1 where user_id=$2',[r,staff]);}
const tickets=(history=false)=>db.query('select public.staff_orders($1) tickets',[history]);
test('kitchen sees accepted tickets without contact, identity or billing data',async()=>{const o=await as(customer,()=>place());await as(staff,()=>transition(o.id,'accept'),{aal:'aal2'});await roleAs('kitchen');const r=await as(staff,()=>tickets(),{aal:'aal2'});const t=r.rows[0].tickets[0];assert.equal(t.id,o.id);for(const field of ['customer_id','customer_name','contact','total_paise','request_id'])assert.equal(t[field],undefined);assert.equal(t.items[0].unit_price_paise,undefined);const raw=await as(staff,()=>db.query('select * from public.orders'),{aal:'aal2'});assert.equal(raw.rows.length,0);});
test('kitchen cannot see unaccepted or bulk-held orders',async()=>{await as(customer,()=>place(11));await roleAs('kitchen');assert.deepEqual((await as(staff,()=>tickets(),{aal:'aal2'})).rows[0].tickets,[]);});
test('kitchen cannot approve, reject, hand over or bypass private transition',async()=>{const o=await as(customer,()=>place());await roleAs('kitchen');for(const a of ['accept','confirm_call','reject','complete'])await assert.rejects(as(staff,()=>transition(o.id,a),{aal:'aal2'}),/staff role/);await assert.rejects(as(staff,()=>db.query("select private.staff_transition($1,'accept','')",[o.id]),{aal:'aal2'}),/permission denied/);});
test('counter cannot change kitchen preparation state or manager settings',async()=>{const o=await as(customer,()=>place());await roleAs('counter');await as(staff,()=>transition(o.id,'accept'),{aal:'aal2'});for(const a of ['prepare','ready'])await assert.rejects(as(staff,()=>transition(o.id,a),{aal:'aal2'}),/staff role/);await assert.rejects(as(staff,()=>db.query('select public.manager_setting(true)'),{aal:'aal2'}),/Manager/);await assert.rejects(as(staff,()=>tickets(true),{aal:'aal2'}),/Manager/);});
test('kitchen transition response is also redacted',async()=>{const o=await as(customer,()=>place());await as(staff,()=>transition(o.id,'accept'),{aal:'aal2'});await roleAs('kitchen');const r=await as(staff,()=>transition(o.id,'prepare'),{aal:'aal2'});assert.equal(r.rows[0].status,'preparing');assert.equal(r.rows[0].contact,undefined);assert.equal(r.rows[0].items[0].unit_price_paise,undefined);});
test('staff read RPC requires membership and MFA',async()=>{await assert.rejects(as(customer,()=>tickets(),{aal:'aal2'}),/Staff access/);await assert.rejects(as(staff,()=>tickets()),/authenticator/);await db.query('update private.staff set active=false where user_id=$1',[staff]);await assert.rejects(as(staff,()=>tickets(),{aal:'aal2'}),/Staff access/);});
test('manager operations are audited and cannot revoke own access',async()=>{await as(staff,()=>db.query('select public.manager_setting(false)'),{aal:'aal2'});await as(staff,()=>db.query("select public.manager_availability('dish',false)"),{aal:'aal2'});await as(staff,()=>db.query("select public.manager_staff($1,'kitchen',true)",[other]),{aal:'aal2'});await assert.rejects(as(staff,()=>db.query("select public.manager_staff($1,'counter',false)",[staff]),{aal:'aal2'}),/own access/);assert.equal((await db.query('select count(*)::int n from private.staff_audit')).rows[0].n,3);await db.exec("update public.menu_items set active=true where id='dish'");});
test('nonmanagers cannot access management data or assign roles',async()=>{await roleAs('kitchen');for(const sql of ['select public.manager_overview()',"select public.manager_availability('dish',false)",`select public.manager_staff('${other}','manager',true)`])await assert.rejects(as(staff,()=>db.query(sql),{aal:'aal2'}),/Manager/);});
