import { useEffect, useRef, useState } from 'react';
import { createClient } from '@supabase/supabase-js';
import './App.css';
const base=import.meta.env.BASE_URL, phone='+918714703888';
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n/100);
const labels={pending_acceptance:'Waiting for restaurant acceptance',awaiting_call:'Call the kitchen to confirm',queued:'Accepted by the kitchen',preparing:'Your food is being prepared',ready:'Ready for you',completed:'Completed',rejected:'Restaurant could not accept this order',cancelled:'Cancelled'};
const active=['pending_acceptance','awaiting_call','queued','preparing','ready'];
const message=e=>/fetch|network/i.test(e?.message||'')?'Connection interrupted. Your bag is safe; please retry.':e?.message||'Please try again.';
let db;
function Captcha({siteKey,onToken}){
 const el=useRef(null);
 useEffect(()=>{let widget,stopped=false;const mount=()=>{if(!stopped&&window.turnstile&&el.current)widget=window.turnstile.render(el.current,{sitekey:siteKey,callback:onToken,'expired-callback':()=>onToken(''),'error-callback':()=>onToken('')});};let script=document.querySelector('[data-turnstile]');if(window.turnstile)mount();else{if(!script){script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.dataset.turnstile='true';script.async=true;document.head.append(script);}script.addEventListener('load',mount);}return()=>{stopped=true;script?.removeEventListener('load',mount);if(widget!==undefined)window.turnstile?.remove(widget);};},[siteKey,onToken]);
 return <div ref={el} className="captcha"/>;
}
function SignIn({config}){
 const [contact,setContact]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[token,setToken]=useState(''),[key,setKey]=useState(0),[retryAt,setRetryAt]=useState(0);
 const isPhone=config.authChannel==='phone';
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{const identity=isPhone?{phone:contact.trim()}:{email:contact.trim()};if(isPhone&&!/^\+[1-9]\d{7,14}$/.test(contact.trim()))throw Error('Enter your mobile number with country code, without spaces.');if(!sent){if(!token)throw Error('Complete the verification check.');if(Date.now()<retryAt)throw Error('Wait one minute before requesting another code.');const r=await db.auth.signInWithOtp({...identity,options:{captchaToken:token}});if(r.error)throw r.error;setSent(true);setRetryAt(Date.now()+60000);}else{const r=await db.auth.verifyOtp({...identity,token:code.trim(),type:isPhone?'sms':'email'});if(r.error)throw r.error;}}catch(e){setError(message(e));}finally{setBusy(false);if(!sent){setToken('');setKey(k=>k+1);}}}
 return <form className="auth-form" onSubmit={submit}><span className="eyebrow">ONE QUICK CHECK</span><h2>A little <em>peace of mind.</em></h2><p>Verify your {isPhone?'mobile number':'email'} before ordering. No password to remember.</p><label>{isPhone?'Mobile number with country code':'Email address'}<input required type={isPhone?'tel':'email'} autoComplete={isPhone?'tel':'email'} value={contact} readOnly={sent} onChange={e=>setContact(e.target.value)} placeholder={isPhone?'+919876543210':'you@example.com'}/></label>{sent?<><label>One-time code<input required inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6,8}" maxLength={8} value={code} onChange={e=>setCode(e.target.value)}/></label><p className="small">A code was requested. If using email, check your inbox and spam folder.</p><button className="link" type="button" onClick={()=>{setSent(false);setCode('');}}>Change details / request another code</button></>:<Captcha key={key} siteKey={config.turnstileSiteKey} onToken={setToken}/>}<ErrorMessage value={error}/><button className="button full" disabled={busy||(!sent&&!token)}>{busy?'Please wait…':sent?'Verify & continue →':'Send verification code →'}</button><p className="small">We use your verified contact details to manage your order. Never share your verification code.</p></form>;
}
function ErrorMessage({value}){return value?<p className="error" role="alert">{value}</p>:null;}
function StaffMFA({onVerified}){
 const [factor,setFactor]=useState(null),[qr,setQr]=useState(''),[code,setCode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{db.auth.mfa.listFactors().then(({data,error})=>{if(error)setError(message(error));else setFactor(data.totp.find(f=>f.status==='verified')||null);});},[]);
 async function enroll(){setBusy(true);try{const {data,error}=await db.auth.mfa.enroll({factorType:'totp',friendlyName:'Onam staff '+Date.now()});if(error)throw error;setFactor(data);setQr(data.totp.qr_code);}catch(e){setError(message(e));}finally{setBusy(false);}}
 async function verify(e){e.preventDefault();setBusy(true);try{const {error}=await db.auth.mfa.challengeAndVerify({factorId:factor.id,code});if(error)throw error;onVerified();}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <section className="panel"><h2>Staff verification</h2><p>Kitchen access requires an authenticator code as well as your sign-in.</p>{!factor?<button className="button" disabled={busy} onClick={enroll}>Set up authenticator</button>:<form onSubmit={verify}>{qr&&<><p>Scan with your authenticator app, then enter its code.</p><img className="mfa-qr" src={qr.startsWith('data:')?qr:'data:image/svg+xml,'+encodeURIComponent(qr)} alt="Authenticator setup QR"/></>}<label>Authenticator code<input required pattern="[0-9]{6}" inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value)}/></label><button className="button" disabled={busy}>Verify staff access</button></form>}<ErrorMessage value={error}/></section>;
}
function Staff({session,config}){
 const [allowed,setAllowed]=useState(null),[aal,setAal]=useState(false),[orders,setOrders]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[notes,setNotes]=useState({}),[sync,setSync]=useState('');
 async function check(){const r=await db.rpc('staff_access');if(r.error){setError(message(r.error));return;}setAllowed(r.data);const level=await db.auth.mfa.getAuthenticatorAssuranceLevel();setAal(level.data?.currentLevel==='aal2');}
 useEffect(()=>{if(session)check();else{setAllowed(null);setAal(false);setOrders([]);}},[session]);
 async function load(){const r=await db.from('orders').select('*').in('status',active).order('created_at').limit(200);if(r.error)setError(message(r.error));else{setOrders(r.data);setSync(new Date().toLocaleTimeString());setError('');}}
 useEffect(()=>{if(!allowed||!aal)return;load();const id=setInterval(load,15000);return()=>clearInterval(id);},[allowed,aal]);
 async function transition(o,action){setBusy(o.id);setError('');try{const r=await db.rpc('staff_transition',{p_order_id:o.id,p_action:action,p_call_note:notes[o.id]||''});if(r.error)throw r.error;await load();}catch(e){setError(message(e));}finally{setBusy('');}}
 if(!session)return <SignIn config={config}/>;
 if(allowed===null)return <p>Checking staff access… {error}</p>;
 if(!allowed)return <section className="panel"><h2>Staff access required</h2><p>The owner has not authorised this account.</p></section>;
 if(!aal)return <StaffMFA onVerified={check}/>;
 const pending=orders.filter(o=>['pending_acceptance','awaiting_call'].includes(o.status)), kitchen=orders.filter(o=>['queued','preparing','ready'].includes(o.status));
 const render=o=><article className="ticket" key={o.id}><span className="eyebrow">{o.id.slice(0,8)} · {o.fulfilment==='pickup'?'PICKUP':'TABLE '+o.table_number}</span><h3>{o.customer_name}</h3><p>{labels[o.status]} · {o.dish_count} portions</p><p className="small">{o.contact} · {new Date(o.created_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</p><ul>{o.items.map(i=><li key={i.id}>{i.quantity} × {i.name}</li>)}</ul><strong>{money(o.total_paise)}</strong>{o.notes&&<p className="order-note">Customer note: {o.notes}</p>}{o.status==='awaiting_call'&&<label>Record the customer call and kitchen confirmation<textarea maxLength={500} value={notes[o.id]||''} onChange={e=>setNotes({...notes,[o.id]:e.target.value})} placeholder="Who you spoke to, agreed items and timing…"/></label>}<div className="ticket-actions">{o.status==='pending_acceptance'&&<button disabled={busy===o.id} onClick={()=>transition(o,'accept')}>Accept into kitchen</button>}{o.status==='awaiting_call'&&<button disabled={busy===o.id||(notes[o.id]||'').trim().length<10} onClick={()=>transition(o,'confirm_call')}>Call confirmed · accept into kitchen</button>}{pending.includes(o)&&<button className="secondary" disabled={busy===o.id} onClick={()=>transition(o,'reject')}>Decline</button>}{o.status==='queued'&&<button disabled={busy===o.id} onClick={()=>transition(o,'prepare')}>Start preparing</button>}{o.status==='preparing'&&<button disabled={busy===o.id} onClick={()=>transition(o,'ready')}>Mark ready</button>}{o.status==='ready'&&<button disabled={busy===o.id} onClick={()=>transition(o,'complete')}>Handed over · complete</button>}</div></article>;
 return <><div className="staff-heading"><div><span className="eyebrow">ONAM VEG · STAFF</span><h1>A good service<br/>starts <em>here.</em></h1></div><p>Refreshes every 15 seconds.<br/>Last update: {sync||'Connecting…'}</p></div><ErrorMessage value={error}/><h2>Requests to review <span className="count">{pending.length}</span></h2><p>These requests are outside the kitchen queue. Check table details and special requests before accepting.</p><div className="tickets">{pending.length?pending.map(render):<p className="empty">No requests waiting.</p>}</div><h2>Kitchen queue <span className="count">{kitchen.length}</span></h2><div className="tickets">{kitchen.length?kitchen.map(render):<p className="empty">The kitchen queue is clear.</p>}</div></>;
}
export default function App(){
 const [config,setConfig]=useState(null),[menu,setMenu]=useState([]),[enabled,setEnabled]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[session,setSession]=useState(null),[category,setCategory]=useState('All'),[query,setQuery]=useState('');
 const [cart,setCart]=useState(()=>{try{return Object.fromEntries(Object.entries(JSON.parse(localStorage.getItem('onam-customer-bag')||'{}')).filter(([id,q])=>/^[a-f0-9]{20}$/.test(id)&&Number.isInteger(q)&&q>0&&q<100));}catch{return {};}});
 const [checkout,setCheckout]=useState(false),[name,setName]=useState(''),[fulfilment,setFulfilment]=useState('pickup'),[table,setTable]=useState(''),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[orders,setOrders]=useState([]),[notice,setNotice]=useState('');
 const requestId=useRef(null),placing=useRef(false),dialog=useRef(null),bag=useRef(null);const staff=new URLSearchParams(location.search).get('staff')==='1';
 useEffect(()=>{let stopped=false,subscription;(async()=>{try{const r=await fetch(base+'config.json',{cache:'no-store'});if(!r.ok)throw Error('Unable to load ordering settings.');const cfg=await r.json();const configured=/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(cfg.supabaseUrl||'')&&!!cfg.supabasePublishableKey&&!!cfg.turnstileSiteKey;if(stopped)return;setConfig({...cfg,configured});if(!configured){const r=await fetch(base+'catalog.json');if(!r.ok)throw Error('Unable to load menu.');setMenu(await r.json());return;}db=createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:false,detectSessionInUrl:false,autoRefreshToken:true}});subscription=db.auth.onAuthStateChange((_e,s)=>{if(!stopped)setSession(s);}).data.subscription;const [catalog,settings]=await Promise.all([db.from('menu_items').select('*').eq('active',true).order('name'),db.from('ordering_settings').select('*').eq('id',true).single()]);if(catalog.error||settings.error)throw catalog.error||settings.error;if(!stopped){setMenu(catalog.data);setConfig({...cfg,configured,authChannel:settings.data.auth_channel});setEnabled(settings.data.enabled);}}catch(e){if(!stopped)setError(message(e));}finally{if(!stopped)setLoading(false);}})();return()=>{stopped=true;subscription?.unsubscribe();};},[]);
 useEffect(()=>{try{localStorage.setItem('onam-customer-bag',JSON.stringify(cart));}catch{}requestId.current=null;},[cart,name,fulfilment,table,notes]);
 useEffect(()=>{if(checkout&&!dialog.current?.open)dialog.current?.showModal();if(!checkout&&dialog.current?.open)dialog.current.close();},[checkout]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(id);},[notice]);
 async function loadOrders(){if(!db||!session)return;const r=await db.from('orders').select('*').eq('customer_id',session.user.id).order('created_at',{ascending:false}).limit(10);if(r.error)setError(message(r.error));else setOrders(r.data);}
 useEffect(()=>{if(!session){setOrders([]);return;}loadOrders();const id=setInterval(loadOrders,15000);return()=>clearInterval(id);},[session]);
 const selected=menu.filter(i=>cart[i.id]).map(i=>({...i,quantity:cart[i.id]})),total=selected.reduce((n,i)=>n+i.price_paise*i.quantity,0),count=selected.reduce((n,i)=>n+i.quantity,0),categories=['All',...new Set(menu.map(i=>i.category))];
 const filtered=menu.filter(i=>(category==='All'||i.category===category)&&(i.name+' '+i.description).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(!!b.image)-Number(!!a.image));
 function change(id,delta){setError('');setCart(prev=>{const next={...prev,[id]:Math.min(99,(prev[id]||0)+delta)};if(next[id]<=0)delete next[id];return next;});}
 async function place(e){e.preventDefault();if(placing.current||!enabled||!session)return;placing.current=true;setBusy(true);setError('');try{requestId.current ||= crypto.randomUUID();const r=await db.rpc('place_order',{p_request_id:requestId.current,p_items:selected.map(i=>({id:i.id,quantity:i.quantity})),p_name:name.trim(),p_fulfilment:fulfilment,p_table:fulfilment==='dine_in'?Number(table):null,p_notes:notes.trim(),p_expected_total:total});if(r.error)throw r.error;if(!r.data?.id)throw Error('No order receipt received. Please retry.');setOrders(prev=>[r.data,...prev.filter(o=>o.id!==r.data.id)]);setCart({});setCheckout(false);setNotes('');setNotice(r.data.status==='awaiting_call'?'Request saved. Call the kitchen before it can be accepted.':'Request saved. Waiting for restaurant acceptance.');}catch(e){setError(message(e));}finally{placing.current=false;setBusy(false);}}
 async function cancel(id){setBusy(true);const r=await db.rpc('cancel_order',{p_order_id:id});if(r.error)setError(message(r.error));else await loadOrders();setBusy(false);}
 const quantity=i=><div className="quantity"><button aria-label={'Remove one '+i.name} onClick={()=>change(i.id,-1)}>−</button><span>{cart[i.id]}</span><button aria-label={'Add one '+i.name} disabled={cart[i.id]>=99} onClick={()=>change(i.id,1)}>+</button></div>;
 return <><div className="announcement"><span>A little Kerala. A lot of heart.</span><span>CHERTHALA · PURE VEGETARIAN</span></div><header className="header"><a className="brand" href="https://www.onamveg.in/" aria-label="Onam Veg home"><img src={base+'assets/logo.png'} alt="Onam Veg"/></a><nav><a href="https://www.onamveg.in/">Our restaurant ↗</a>{!staff&&<button onClick={()=>bag.current?.scrollIntoView({behavior:'smooth',block:'start'})}>Your bag <b>{count}</b></button>}{session&&<button onClick={async()=>{await db.auth.signOut();setSession(null);setName('');setOrders([]);}}>Sign out</button>}</nav></header><main className={staff?'staff-main':''}>{staff?(!config?.configured?<section className="panel"><h1>Staff setup <em>pending.</em></h1><p>The owner needs to connect authentication and the database first.</p></section>:<Staff session={session} config={config}/>):<>
 <section className="order-hero"><div><span className="eyebrow"><span className="veg">●</span> FROM OUR KITCHEN TO YOUR TABLE</span><h1>Your favourites.<br/><em>A few taps away.</em></h1><p>Golden dosas, comforting curries and a little taste of home.<br/>Choose your dishes. We’ll take care of the rest.</p><div className="hero-meta"><span>✳ Pure vegetarian</span><span>Pickup & dine-in</span><span>Pay at the restaurant</span></div></div><div className="hero-image"><img src={base+'assets/sadhya.webp'} alt="Kerala sadya on a banana leaf"/><span>GOOD FOOD.<br/><em>Good mood.</em></span></div></section>
 {!loading&&!enabled&&<div className="service-notice"><span>✳</span><div><strong>Explore the menu. Ordering opens soon.</strong><p>This proof of concept isn’t accepting orders yet. Call <a href={'tel:'+phone}>+91 87147 03888</a> for assistance.</p></div></div>}
 <div className="order-layout"><section className="menu-area"><div className="menu-heading"><div><span className="eyebrow">A LITTLE OF WHAT YOU LOVE</span><h2>What are you <em>craving?</em></h2></div><label className="search"><span>⌕</span><input aria-label="Search dishes" placeholder="Find your favourite…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="categories" aria-label="Menu categories">{categories.map(c=><button key={c} className={category===c?'active':''} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="menu-count">{loading?'Getting the menu ready…':filtered.length+' dishes to make your day'}<span>All prices in INR</span></div>{!checkout&&<ErrorMessage value={error}/>}<div className="dish-grid">{filtered.map(i=><article className={'dish '+(!i.image?'text-dish':'')} key={i.id}>{i.image&&<img src={base+i.image} alt={i.name} loading="lazy"/>}<div className="dish-body"><span className="dish-category"><span className="veg">●</span> {i.category}</span><h3>{i.name}</h3><p>{i.description||'A little taste of our kitchen.'}</p><div className="dish-bottom"><strong>{money(i.price_paise)}</strong>{cart[i.id]?quantity(i):<button className="add" onClick={()=>{change(i.id,1);setNotice(i.name+' added to your bag');}}>Add +</button>}</div></div></article>)}</div>{!filtered.length&&!loading&&<p className="empty">No matching dishes. Try another category or search.</p>}</section>
 <aside ref={bag} className="bag"><span className="eyebrow">A LITTLE HAPPINESS, TO GO</span><h2>Your <em>bag.</em> <span className="count">{count}</span></h2>{!selected.length?<div className="empty-bag"><span>✳</span><h3>Good things belong here.</h3><p>Add a few favourites to get started.</p></div>:<><div className="bag-lines">{selected.map(i=><div className="bag-line" key={i.id}><div><h3>{i.name}</h3><small>{money(i.price_paise)} each</small></div>{quantity(i)}</div>)}</div><div className="bag-total"><span>Menu total</span><strong>{money(total)}</strong></div>{count>10&&<div className="call-note"><strong>A big meal deserves a quick call.</strong><p>Over 10 portions? Your request stays on hold until you call the kitchen and staff confirms it.</p><a href={'tel:'+phone}>Call +91 87147 03888 ↗</a></div>}<button className="button full" disabled={!enabled||count>100} onClick={()=>{setError('');setCheckout(true);}}>{!enabled?'Online ordering opens soon':count>100?'Call us for more than 100 portions':'Review & verify →'}</button><p className="small">{enabled?'Verified details. Restaurant confirmation on every request.':'Your bag is saved on this device. No order has been sent.'}</p></>}
 {!!orders.length&&<section className="my-orders"><h3>Your recent orders</h3>{orders.map(o=><article key={o.id} className="receipt"><span className="eyebrow">{o.id.slice(0,8)}</span><h4>{labels[o.status]}</h4><p>{o.dish_count} portions · {money(o.total_paise)}</p>{o.status==='awaiting_call'&&<a href={'tel:'+phone}>Call kitchen to confirm ↗</a>}{['pending_acceptance','awaiting_call'].includes(o.status)&&<button className="link" disabled={busy} onClick={()=>cancel(o.id)}>Cancel request</button>}</article>)}</section>}</aside></div></>}
 </main><footer><a href="https://www.onamveg.in/">Onam Veg · From Kerala, with love.</a><span>Need a hand? <a href={'tel:'+phone}>+91 87147 03888</a></span><a href={staff?base:'?staff=1'}>{staff?'Customer menu':'Staff sign-in'}</a></footer>
 <dialog ref={dialog} onCancel={()=>setCheckout(false)} className="checkout"><button className="close" aria-label="Close checkout" onClick={()=>setCheckout(false)}>×</button>{checkout&&config?.configured&&!session?<SignIn config={config}/>:<form onSubmit={place}><span className="eyebrow">ONE LAST LOOK</span><h2>Make it <em>yours.</em></h2><p>{count} portions · {money(total)} · Pay at restaurant</p><label>Your name<input required minLength={2} maxLength={80} autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label><label>How are you dining?<select value={fulfilment} onChange={e=>setFulfilment(e.target.value)}><option value="pickup">Pickup at the restaurant</option><option value="dine_in">I’m seated at a table</option></select></label>{fulfilment==='dine_in'&&<label>Table number<select required value={table} onChange={e=>setTable(e.target.value)}><option value="">Choose your table</option>{Array.from({length:10},(_,i)=><option key={i} value={i+1}>Table {i+1}</option>)}</select></label>}<label>Anything we should know?<textarea maxLength={500} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Special requests or pickup timing…"/></label><p className="small">For allergies, speak directly with staff before ordering. Special requests depend on kitchen confirmation.</p>{count>10&&<div className="call-note"><strong>Kitchen call required</strong><p>Your request stays on hold until you call <a href={'tel:'+phone}>+91 87147 03888</a> and staff records confirmation. Tapping a call link alone does not approve it.</p></div>}<ErrorMessage value={error}/><button className="button full" disabled={busy||!enabled||count<1||count>100}>{busy?'Submitting securely…':count>10?'Request kitchen confirmation →':'Submit for restaurant acceptance →'}</button></form>}</dialog>{notice&&<div className="toast" role="status">{notice}</div>}</>;
}
